import "./globals.css";
import Providers from '../providers';

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({children}) {
  return (
    <html className="h-full " lang="en">
      <body className={`h-full`}>
        <Providers>
          {children}
        </Providers>
      </body>
    </html>
  );
}
